apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
  namespace: database
type: Opaque
stringData:
  #ENC[AES256_GCM,data:H5A4aiZeu+B3mdLD432tsRg=,iv:hbYBu9GZJbnt5dzh/d4dohsofpCPKK21rGDi3588WUU=,tag:29RnuRlhu3O4RLLo3NLgjw==,type:comment]
  username: ENC[AES256_GCM,data:Zo0tUdzr4VM=,iv:w9Hn0BKkYrdTwrlRi1D7Qs6TrsIZGNC1kATZj2MlTso=,tag:5780f1aFqLwsVxMgs/S4AQ==,type:str]
  password: ENC[AES256_GCM,data:B49obEToKRgwARUXK5Yk470JXs1T4lh7NRkgJERzvRdislyDvw8aHAuyscrqQQADmSNObSf+OD1dtuGh3oMnGQ==,iv:Ilt5KRPiA1lPQGwNPqxkQ25w6HkG9gRIP/KoN8Grdlc=,tag:KIy3pOTWdZ6vsF0T2DkIIw==,type:str]
  #ENC[AES256_GCM,data:JHDJpNGz+ZXFcqDvkJVQRQN358ERBqHB,iv:PzjZOGebjI73M6nXXu530jLsi1YUuEvt0QyRNlU+Dwo=,tag:5KO1uXAIYbQ9idiJVC1kUA==,type:comment]
  wasabi-id: ENC[AES256_GCM,data:bV2ReczsGv8s6YSsli7Q1LcpFFY=,iv:VD8FVQo+ZhMmVgY2JfMp3//+/uH3J72ihtPAHlLKJWo=,tag:Mti0HwC+QlH6sV4HoNnH+w==,type:str]
  wasabi-key: ENC[AES256_GCM,data:NiDOiiKmy6ooP3FKhujNn8o8Ak+TEFmTeccfG03XuQJf+OUEo8vVtw==,iv:yTT7wBoq81fV2HpkjRRZxYLB9iO3bV3sS6/nIln5pYY=,tag:f43kVBccznQ5BOpdpkEqYg==,type:str]
sops:
  age:
    - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbC9IcEZMMStnQkdBMEdl
        NmxveFA3Zys2RUtkSkkyaEVZNzZFenNuWmpzCmExQ09ZNEllcVludTg3VGRFOVNu
        RzY0ZzdtSmgyNWxvblBQZi91S2hEak0KLS0tIFdJME11MzNrOWRMS2dzM0EzVDNu
        Z2ZrdTFFVlpwYm1JVUwveUxDK3hqNFUK2Q4FACw9nPO8ruly9XyHLcETkvJbrrtk
        6/Q22vUEWfIbNgtszrmsLYfmuO540YtCCH8Uztek0ywYuRFsa0Lwtw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-16T12:23:37Z"
  mac: ENC[AES256_GCM,data:mdJZq8h3Wn3YP+Ul6GAHrVBSQQ+c++CphQJzEqFrSAjNkXXc4D6J1AhgSfKdpeWEFG9QTsIMPTMPBmYUsDdAcTP1lAvVkESlyfKAv9Al/aheJMCAPku9QG0KFUuyI+l0oEfKWY8sJYwONQIiRuprYo84WDJ4tpiF++/PU+0SX9o=,iv:Frz/viQjTwYy+Mo8f0SCdrrPnhqNQRNXiN2ydcGf7TI=,tag:KiNaGmlQpgQ8XNXNMYJKQQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-app-user
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:PypT,iv:MDxOm8jEovklxZ9Q+cBLNRXKZZReBCnztT4McTA+26o=,tag:2a11//tidPLOEE3vQNdXLQ==,type:str]
  password: ENC[AES256_GCM,data:+YFDy/rL80XAZwPMrUKubTHPSa8=,iv:VlAsumXufJjIUntnMsbzwO9j+Lk5FV9KagB2xZj0+NM=,tag:pBRptEsHdcqFL3zJi0rvIA==,type:str]
sops:
  age:
    - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbC9IcEZMMStnQkdBMEdl
        NmxveFA3Zys2RUtkSkkyaEVZNzZFenNuWmpzCmExQ09ZNEllcVludTg3VGRFOVNu
        RzY0ZzdtSmgyNWxvblBQZi91S2hEak0KLS0tIFdJME11MzNrOWRMS2dzM0EzVDNu
        Z2ZrdTFFVlpwYm1JVUwveUxDK3hqNFUK2Q4FACw9nPO8ruly9XyHLcETkvJbrrtk
        6/Q22vUEWfIbNgtszrmsLYfmuO540YtCCH8Uztek0ywYuRFsa0Lwtw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-16T12:23:37Z"
  mac: ENC[AES256_GCM,data:mdJZq8h3Wn3YP+Ul6GAHrVBSQQ+c++CphQJzEqFrSAjNkXXc4D6J1AhgSfKdpeWEFG9QTsIMPTMPBmYUsDdAcTP1lAvVkESlyfKAv9Al/aheJMCAPku9QG0KFUuyI+l0oEfKWY8sJYwONQIiRuprYo84WDJ4tpiF++/PU+0SX9o=,iv:Frz/viQjTwYy+Mo8f0SCdrrPnhqNQRNXiN2ydcGf7TI=,tag:KiNaGmlQpgQ8XNXNMYJKQQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
