---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lidarr-cache-warmer
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      lidarr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/devianteng/lidarr-cache-warmer
              tag: latest
            env:
              TZ: "Europe/Amsterdam"
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 4Gi
    persistence:
      data:
        existingClaim: lidarr-cache-warmer
        globalMounts:
          - path: /app/data
