---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app vaultwarden
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: vaultwarden/server
              tag: 1.34.3
            env:
              DATA_FOLDER: config
              TZ: Europe/Amsterdam
              SIGNUPS_ALLOWED: "false"
              DOMAIN: "https://bw.${SECRET_DOMAIN}"
            envFrom:
              - secretRef:
                  name: vaultwarden-secret
            resources:
              requests:
                memory: 512Mi
                cpu: 10m
              limits:
                memory: 1024Mi
    service:
      main:
        controller: main
        ports:
          http:
            port: 80
    route:
      app:
        hostnames:
          - "bw.${SECRET_DOMAIN}"
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
    persistence:
      config:
        existingClaim: vaultwarden
