apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
type: Opaque
stringData:
  ADMIN_TOKEN: ENC[AES256_GCM,data:2kg5BUjcTlxd4bM/HGvYPFXZuL0GOoRWZa1tHP2GCpYfxQe0iOwBs0b5wbdbI7wryZxuYlpa6rah8hD62mzDZA==,iv:kLXtpMeGsV64E/IQdB7F58x3KproTxRvLMPY2iDuJkE=,tag:x1kwoGXYwLJqFy6csTLcnA==,type:str]
  YUBICO_CLIENT_ID: ENC[AES256_GCM,data:qMvjZh4=,iv:hhjL7p9WmFf1uUAB3hnSB7wKva9DUexWkURnfdpXhxY=,tag:3y5s0ILTJtvpQEIGO/aRcQ==,type:str]
  YUBICO_SECRET_KEY: ENC[AES256_GCM,data:3fF2zXIHaLcONwl0yM8IBuNOe8aDIvxfCG9iBQ==,iv:YZ89RjR5bt/oCFd1bOXHAfs17TVJhMRd0/793UfK5ls=,tag:U2BFaIEGmg+Dq9Zw5+RAiw==,type:str]
sops:
  age:
    - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMHpOc2JYUDJsZDZ3SEp1
        QnQ1ZjE5eVhjRjJwRVZBaEZIOFMwZUJkTEU4Cjk4UlZPT2M5NU9QS3IwTWt1RHVG
        MlM3eEEwRFg2bkpWc2NFdDFKNWh2bEUKLS0tIEdDZWlaYmVycnpKTVFqQTBmN1ZD
        S21JaU4rUUFRdUhFQ1FHV2dBSXQ2d28KYOvBEx0R/W4Wk7IcbI7ElbnSYuQnft4w
        2jjTqJwpbO97HqHFz2HmvCeNcjpRXxBwUb8zUa/8u7GdnUwJO3ihCQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-24T17:30:59Z"
  mac: ENC[AES256_GCM,data:N/TSfC76Yw9niLQ0NqWgGIJOhGShRHfVbEbtF3CME7+IjYOpksCX5r2Q4wrAl5tgA0p170AbrHp7ZpM94m76+CrVmn4zLRi7xhGby/ogQL/F6yuZjwtDMVaPUMaE809HlpiP29essZg/J+qr5TnQNDmGgdkJNjXthiPJcDxzMws=,iv:uSbxE31sg9Xs7Ful55shqNjDIBvQCMDw5pA9U5KBVWc=,tag:gpYC8vNGTrfmf5y1Zs4kkA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
