apiVersion: v1
kind: Secret
metadata:
  name: atuin-secret
  namespace: utilities
type: Opaque
stringData:
  ATUIN_DB_URI: ENC[AES256_GCM,data:j4ZXbfpCyXBp7L0/K5iFLOJiTdhrGbvq0u7e2LjtwOYUQEykec3LRq3EaKIVpu/25tuJ4lrcVy+G/8tnI8xz+aiyN6An+9oKeysEtOapQuWdHGCpXqop9Hzi,iv:GXzwNn6Qv+cNvoMQX6uDc1rWkUReEo0DA7G8E9A8mnE=,tag:mqPrbvRfhY7TkSN34NxT6Q==,type:str]
sops:
  age:
    - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJaDJqSU9YcG93MG93ZnBn
        OVd1VU9vSmRMRmovVXBaMyt2YzA5V2JMZ0dFCkk0MjZ2czl1a3pMczFaNkR4UlVo
        b0FlSFlOTURxSTViOUNQV0xoN05GbVkKLS0tIGt1R2hmREx6ZVZkZkRHRnJ2Zno2
        UWcvK3hsUm9tS0VSaFhVTmhtS2dhZUEKn8d0/1RoEWi89+sd7nI9TuFI+N4V8RCY
        7oKicdeXdP0Oa5sJUUphtPIRVWLeRqlPHGT5GqBo0i7+H1nXiYR+Dg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-19T19:44:24Z"
  mac: ENC[AES256_GCM,data:pUsqZzKbNXNkxHuSPHqhv0vRz5HV7FERCbec6/HmFdzA+CDghw9bua8SIQmyb1qRUYc7ApZvhTp1NBC7w/Az8Gz8B9Lq1Up9RmuuOF1/w6nO1feSvYF/9DjMrjYUpki42hUY2caxMJZkazRZS3soFT9ta2OU46UsCdpu0/ofXQg=,iv:7dSLyvu+RFaCErPeS8IFHBDOG9dmw9wLJIfyeKbTKO8=,tag:gNcvULikFG8PZeyAfmobAw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
