# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:yqSIEzV0/E5IUnuKKOaO1Xel0U9mWyp/qLy/d0ZfLP6/LdiTRUSmGQ==,iv:C2UTJzPplxef+eP+3peEMAWhaqctekqZLz1o2sZxQw8=,tag:EUbAId7iRx82HK3biA4dSw==,type:str]
sops:
  age:
    - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcjdiZDZUbWU1RWpCVHhV
        YUl2eGZQVUdBYmVQTkIxczc4ZkEwajhicVJrCk9YZ2c1UVFUMWhOek9TblVqSzR5
        Y1NMRjFSeGpJaHpMdGFIYzFPVlZVOVkKLS0tIFRRcE44SHIxQzhaSWMyWUF2dmdI
        ZExWMHhZaWRoYXdXclp4TTBZZnFKUk0KLraDbXtV9jttpcUo/9L19CynRdvB8ZIC
        JTI6yB45gs9/27CMVWwmoHyyaTx5/quDM+o9LgilsGZYrcP93OvUjw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-14T18:27:00Z"
  mac: ENC[AES256_GCM,data:FsiH+tRy8sg/jn9Jxqwqb2RERC3cK/rKffKlCrg2mpYvDNDINtrd+IfQI2SqODvmCzJjHmxN9hv/V+DRitr34QTvz2x8tymD60CHNzUFR6+xw1WqRo0XVhMO+GMCypGpLpTunT0CDZw9Hy7xp41jGs5NU5w1VSs/vkT94spYFM0=,iv:5C5WBHKOURHva+0EW66sxVYz+kg7jbad2dOgu+ITmfc=,tag:YCrQu7KPIv91BLNJ4VhVWg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
