---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app user-apps-lidarr-cache-warmer
  namespace: &namespace media
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/media/lidarr-cache-warmer/app
  dependsOn:
    - name: cluster-apps-longhorn
      namespace: storage
  prune: true
  postBuild:
    substituteFrom:
        - name: cluster-secrets
          kind: Secret
        - name: cluster-settings
          kind: ConfigMap
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: true
  interval: 1h
  retryInterval: 1m
  timeout: 5m
