---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app user-apps-bazarr
  namespace: &namespace media
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/media/bazarr/app
  dependsOn:
    - name: cluster-apps-longhorn
      namespace: storage
    - name: cluster-apps-cloudnative-pg-cluster
      namespace: database
  prune: true
  postBuild:
    substitute:
      APP: *app
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - name: cluster-settings
        kind: ConfigMap
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: true
  interval: 1h
  retryInterval: 1m
  timeout: 5m
