apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
type: Opaque
stringData:
  admin-user: ENC[AES256_GCM,data:wQKclt1y0w==,iv:jIb+7sUYy+1/jCBpfmXFMKT0DcwVVOwrPUCl9e/1XxM=,tag:UoBAc2x2wvViKPi//Renow==,type:str]
  admin-password: ENC[AES256_GCM,data:UpZS9N/sq/1TCprUm4zG4bSwFhlh5DkUzOvVvHCbQDmgFUE36XlhetWf1v5/iS62aHNqrW6XL+MW7GMHAqZgsQ==,iv:tA5X05veuPNLL8D8CsFu80eVEyz6NjBPbMMc5hZWbHU=,tag:iHJw167n0zZKmcO+0sKMXg==,type:str]
sops:
  age:
    - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdjRMMzBaZXdOamMva2t2
        VzgySWd3Ui8wWDlOK0lMU1dMRkZoUlVtRTFVCmNSNjVDcWZ4RVlZVE9ESzJaTHlt
        OWtnRFJ1a2gxZ2UxdjhVcklVNFJvNVUKLS0tIG1DTENRYW5wY1hLUmh6SzBmendV
        MkJUYml2M292ZmpYb3JVNEsyTkw5eFkKJS2sUWoM5D3N/1Oz+kKH2ifVL/QFeEib
        1WilqyXoBwEmVnj9xYdJESeWzMvBklMoTUcJxrjcRQMNgMgrD03MCg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-31T20:42:44Z"
  mac: ENC[AES256_GCM,data:09USyLQDpXtuIH/JPTOBnke9vImA1QyN7fPp/2kw8P5ftXIfeOO31ZExyhjS2aoY7ztCLvkX4qziDRb2JhNvviQhkaDmtaf5EEU5JOMxDdsuACBDX1firgYui34OM3bWVC4CjS881/IjCKsZCNdYOBj5oFdY29oLEU7bp2u302M=,iv:zRpx15Zqj1tW40DSUdY3wi2830yRaziiRiwrbBW9SgE=,tag:Kdp9OcyAKYldOjIVZezXdA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
