apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:wQKclt1y0w==,iv:jIb+7sUYy+1/jCBpfmXFMKT0DcwVVOwrPUCl9e/1XxM=,tag:UoBAc2x2wvViKPi//Renow==,type:str]
    admin-password: ENC[AES256_GCM,data:UpZS9N/sq/1TCprUm4zG4bSwFhlh5DkUzOvVvHCbQDmgFUE36XlhetWf1v5/iS62aHNqrW6XL+MW7GMHAqZgsQ==,iv:tA5X05veuPNLL8D8CsFu80eVEyz6NjBPbMMc5hZWbHU=,tag:iHJw167n0zZKmcO+0sKMXg==,type:str]
sops:
    age:
        - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdjRMMzBaZXdOamMva2t2
            VzgySWd3Ui8wWDlOK0lMU1dMRkZoUlVtRTFVCmNSNjVDcWZ4RVlZVE9ESzJaTHlt
            OWtnRFJ1a2gxZ2UxdjhVcklVNFJvNVUKLS0tIG1DTENRYW5wY1hLUmh6SzBmendV
            MkJUYml2M292ZmpYb3JVNEsyTkw5eFkKJS2sUWoM5D3N/1Oz+kKH2ifVL/QFeEib
            1WilqyXoBwEmVnj9xYdJESeWzMvBklMoTUcJxrjcRQMNgMgrD03MCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-22T19:30:28Z"
    mac: ENC[AES256_GCM,data:oyaFZezmaousHxYVsKiiwQptZjPraHtAisQQcLNov+TDpJzyJqSGApo5/wZyj2RcTnv+7zM7ZkABJXj3avT+t841mWfJpIV02W7AViRETdLma2gvuNT5go6NsKH/aCyYuksWGyUzO6HqviiORnsb/oongtS38ZK6I+QJZIkLiOY=,iv:T00eWDy7HNMfPH1oVE/bzI1GM7Hz+65RtACsNb8UdP4=,tag:HDH8WsvTkxEu/ocaMBPFiw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
