apiVersion: v1
kind: Namespace
metadata:
  name: home
  labels:
  # Lower security standards for the `home` namespace so we can use ICMP
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: v1.33
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/audit-version: v1.33
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/warn-version: v1.33
