apiVersion: v1
kind: Secret
metadata:
  name: gatus-secret
  namespace: observability
type: Opaque
stringData:
  GATUS_POSTGRES_PASS: ENC[AES256_GCM,data:QgGRcM1d4ZcSRSmxP23BDQyaWhl4MMMAJvb6+Duen1a8z6gMGRakTaW4HdS1NzaWoADnWVxVc5dGbd89RKIl6w==,iv:OlAYVUgwmNOmY/gAzXtPjBNfbdPnFhC0ruRSfVHFrv8=,tag:Fnhc8qslxxXixbOPiidigA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZG9mclhOZ2M5aUtlTWV5
        V2tOdVpOdGF3LzlSY0VBN0hGREdzK3RrT3pRCkRPcDJNWThRT0hwMUVxVlZOdEFa
        U0o3UnhBZXhNUE1BamMwMEZGRzBUZ0kKLS0tIGt5d3lCelVMeXB1MHJrek1rd2Fv
        UEZBWkJ5VTNGQW1GcTNLS3N4TWdhQk0KpOOY+8YgefIfXvsW+F4GHNVScuWpmuGX
        bCPs1bUIQQf/f56j9zCGQBY0O7QQwvNj13XCAEPiwZPVbMu9d3IcSA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-15T09:28:00Z"
  mac: ENC[AES256_GCM,data:xuTU50H61jo1ytFZsQcCDOJ3bD/YYohWcSn/jJTbhERJ91TzQKGbjTATgQaH5iImtubtDlTgdGZWfTvYGYDa7pADBcxytRWZEV5FJ79rhbA/EyRfohntWfPVPh63XcpY9fJGx91XjzG9u+uHh6Wn2adfyPJlaZgpJ/okOAR73YY=,iv:XXxAPDKugSDI4WyRzj86aWmOhqfa+6qy6816PyEdm4w=,tag:vipqViSX1R0adXW24ec74g==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
