---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 30m
  chart:
    spec:
      chart: openebs
      version: 4.3.3
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    localpv-provisioner:
      localpv:
        image:
          registry: quay.io/
      hostpathClass:
        enabled: true
        name: openebs-hostpath
        isDefaultClass: false
      helperPod:
        image:
          registry: quay.io/
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "nodeType"
                    operator: In
                    values:
                      - "pi"
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
    openebs-crds:
      csi:
        volumeSnapshots:
          enabled: false
          keep: false
    zfs-localpv:
      enabled: false
    lvm-localpv:
      enabled: false
    mayastor:
      enabled: false
    minio:
      enabled: false
    loki:
      enabled: false
    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: false
