---
endpoints:
  - name: "${APP_NAME:=${APP}}"
    group: External
    url: "https://${GATUS_SUBDOMAIN:=${APP}}.abchost.nl${GATUS_PATH:=/}"
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == ${GATUS_STATUS:=200}"
