apiVersion: v1
kind: Secret
metadata:
  name: radarr-secret
  namespace: media
type: Opaque
stringData:
  RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:O/4pq73zkHtzWjtQH0MqiURvSNJoNJ+t7EFMH08NyqM=,iv:A30XDolCvzdYxQIR/ouzyycyVVKlMPEvJnqpgJW2d00=,tag:J25VeDNV+REUiEV04t2jrg==,type:str]
  RADARR__POSTGRES__HOST: ENC[AES256_GCM,data:jnC0sXEicInV6afRcbWPNPjJZReaHug+6+8wjWkqyYrMjinMDeVOPQ==,iv:9KyrNLs9gh9fwEirGscyFXGg5LykLjfD2r0ciCj4/Uk=,tag:JN6XYmP8tS3WwM41rbQWPA==,type:str]
  RADARR__POSTGRES__PORT: ENC[AES256_GCM,data:ZoOtNw==,iv:851OEGYLN5I7ONoLSCMc8pg0YDgLyOKSs7Ho7ghyIW4=,tag:7T6pRZ4K585wb50ZmvGNug==,type:str]
  RADARR__POSTGRES__USER: ENC[AES256_GCM,data:G9e0hTbO,iv:/A1G8PvtU/vLZrVtCiN3nKN3PPxTSP3V0h+XE7vdkhA=,tag:Mzya+lxhfjZ4Db2PWUDJuQ==,type:str]
  RADARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:alMKlbjTWrgtwlXryTCIW4XByFmOy7x78ktpTz9N/mNi4omMyqMYMw==,iv:Uh0zR9Zmn3vFvtjXZvFjKLf5ZZGRb8owl3wighmWOf0=,tag:Al35pvn1wR3FT5uHUM+f/w==,type:str]
  RADARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:CYezp1Iqw9hqidk=,iv:N2SfgsLB9aCVpT7bXFMUKRRsrDZIorhMicQBcn0TeSA=,tag:dbUyoH1rTk0lFpq2zIv5LQ==,type:str]
  RADARR__POSTGRES__LOGDB: ENC[AES256_GCM,data:wO8YKm46+UXgfQ==,iv:Ms+KCHhbs3RXRS2w5QbEv2EU2IlamckY1FMnSRpen/c=,tag:AKuFTXexxeoQUKbosjumvQ==,type:str]
sops:
  age:
    - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWUU0YU1Qc2NSN2VzUk1m
        akQzL29JN0FJNm15aUVld3Jxb1E4cXlaNGdJCkFWSE1Vb293QVNHU2NWTWZpdFlk
        TU9IS1dxeEUvZVorUmtnSFM2Wm9vRWMKLS0tIHUyazdtT29jVGZYd2NZUWJCL1dX
        bWV6ZXBqM2tjY0lLNGNMODVjeEZyNFUKFE3V5JKkMvsbXmMsjdAHf6WfsoNA3v8S
        B6wVuRcRvFmn4mVCVQCMt7JTJg7Ttv0ymYK+Oe0JJLQW3BPjL/BqFg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-24T12:12:51Z"
  mac: ENC[AES256_GCM,data:BTc5LJxulY1/oJNEjGDOrhcd4i1wiOEJI6ZTjmI6oaxNn3g5q0oplpT5PiXsJS+6Raz8xYE7ahlTCRRHW3Hg+tjkc0YB7d7KojCjyeFrlNAkCXFbg99Enxcr58uwMKZsawIta0zcQrxYsG1yK9PssscjygK0ou0YGlT0bR+HWOg=,iv:kbQcfaDHPdIhuhyixadsXg/IrB1ZvZWa2MMIHtIvCZA=,tag:slxvaWw2hqEW2+kifHqdxA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
