---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app user-apps-qbittorrent
  namespace: &namespace download-clients
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/gatus/guarded
  path: ./kubernetes/apps/download-clients/qbittorrent/app
  dependsOn:
    - name: cluster-apps-longhorn
      namespace: storage
  prune: true
  postBuild:
    substitute:
      APP: *app
      APP_NAME: "QBittorrent"
      GATUS_SUBDOMAIN: torrent
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - name: cluster-settings
        kind: ConfigMap
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: true
  interval: 1h
  retryInterval: 1m
  timeout: 5m
