# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:k78QfPoKNODSKAfciAKhqQvwdLBJVI0RwTnrr/g/D29OsNsbqkTaJg==,iv:10pyRAW3uK6CQf3kyfTQBj5tDhoiaomxbgNHe5PLZdY=,tag:EjzfruGXvXmi5eJY55yOyQ==,type:str]
sops:
  age:
    - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDS0FCWExoMFpNRW1pTTJQ
        MnIrMFlqczllWW5JZHg4R1Z6Y0s4eE8xeGhZCjhlY3FQV25MSFNYa1hMemtHUm4y
        Q1NXNW9HeHNMOVdTQlQ2U29DNEJzYk0KLS0tIEtBWFNldnVsTmVjMENDdVdSdmQw
        TllDWUw1bFNSclkwVHVxdzEwUWMvUDgKjYemfEbUCA3W8MgkQc7QK4e08v9HBCTq
        SaFakgs/knUt41mQn8mjYL1my7QMUVPddujefsARz+qiiQyB2fQHGQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-28T16:18:34Z"
  mac: ENC[AES256_GCM,data:XJmLEOrhZlsoVmyqnxh7bXQZQlO8p/qle6xGSw6z6UBqY1iw6YlE+LMRnnzpmjGFYkbmtn6pFrhqQrsseUlFpe9ZuWbq9VjYQpFC5eVQLjBGOSOzsmQ2H15XDE6wETmB5O2/1K1ajUEiv1/wXMADejFQfJ0QE4V3hNARpGfkl/A=,iv:vwHNh9u/Gnh+x/DchnEdW0H/nXGJ5rGybSitbmiJJ20=,tag:kbaJImp/0P06Q9TPKrvHag==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
