---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app user-apps-mealie
  namespace: &namespace utilities
spec:
  dependsOn:
    - name: cluster-apps-cloudnative-pg-cluster
      namespace: database
    - name: cluster-apps-longhorn
      namespace: storage
  path: ./kubernetes/apps/utilities/mealie/app
  postBuild:
    substitute:
      APP: *app
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - name: cluster-settings
        kind: ConfigMap
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
