machine:
  logging:
    destinations:
      - endpoint: "udp://10.0.2.128:5171"
        format: "json_lines"
#        extraTags:
#          node: "{{ .MachineConfig.MachineNetwork }}"
---
apiVersion: v1alpha1
kind: KmsgLogConfig
name: remote-log
url: udp://10.0.2.128:5170

