endpoints:
  - name: "${APP:=${APP_NAME}}"
    group: Guarded
    url: 1.1.1.1
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    dns:
      query-name: "${APP:=${GATUS_SUBDOMAIN}}.abchost.nl"
      query-type: A
    conditions:
      - "len([BODY]) == 0"
