apiVersion: v1
kind: Secret
metadata:
  name: zigbee2mqtt-secret
type: Opaque
stringData:
  ZIGBEE2MQTT_CONFIG_MQTT_USER: ENC[AES256_GCM,data:5X0eDmO9kFQ4Yvc=,iv:1Ty2y7XVyixvMMzYUfehRSnIpxII9AaLIw5JKjwFuPk=,tag:375ZuYyQXJsiw4NnARm+lQ==,type:str]
  ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: ENC[AES256_GCM,data:4BaJQiWf3rXEeLnuBv37XWwZyw8b6IgDS0zHNwF8AV8=,iv:5UDtZv7uYjRRhTSeKbQ60Tt5caoXg9fiwnHYW/Xyetk=,tag:74EkLFAL/u261NUV6fslHw==,type:str]
sops:
  age:
    - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WS9aeU52UElyTFhkYnFY
        ZWs0T1RGdGF0aGFpRUxEQ0prM3FTbmlaYWhvCkVIRmNsK2RjYmpGbzBMdGFYcGc5
        aHRKRUYzZUhWRFo1azNuRXZDRmNqK2MKLS0tIDNrV3ZoZ1hwSFBWQjlqY2t0SDNE
        SWtqaENRRVQ0R2FqU3ZUNGhlVUVIcGMKLuFVoYLRdoyOBa82Z4PiZAWLnzQnS8EV
        k/g2MZxbBGIA6w7TiuY4xdiZA2nm89OClk9VBPzrYqnwuDWHtL32Lw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-18T16:52:49Z"
  mac: ENC[AES256_GCM,data:ckdioTKy+xzdE4sUR7FU/ZZBfb4mJT5pNaTXpsaOHTz9OZ/67Ad8A/5omca1isX1n5rMDmHa95R9Cr1QXRVcOGLxxRa1kPaYwpuZlV5CbwrsZ5keJoxSgnEU5fuW05GzJJRYrYqhTt8FJJlrD7lTUSgfYNIovAwk8C44iPeH6qc=,iv:sNMl5hI1aWevNDSUqx+gFFNRRauodIqvEiZWDRhexLQ=,tag:cEdW2Nm87d1BE3fgBpR1WA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
