---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 15m
  chart:
    spec:
      chart: longhorn
      version: "1.11.0"
      sourceRef:
        kind: HelmRepository
        name: longhorn
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  # https://github.com/longhorn/longhorn/blob/master/chart/values.yaml
  values:
    image:
      longhorn:
        instanceManager:
          tag: v1.11.0-hotfix-2
        manager:
          tag: v1.11.0-hotfix-1
    persistence:
      defaultDataLocality: best-effort
      reclaimPolicy: Retain
    defaultSettings:
      dataEngine: v2
      v1DataEngine: false
      v2DataEngine: true
      allowRecurringJobWhileVolumeDetached: true
      orphanResourceAutoDeletion: "replica-data;instance"
      backupTarget: "s3://longhorn.mizuto.backup@eu-central-1/"
    metrics:
      serviceMonitor:
        enabled: true
    ingress:
      enabled: false
    defaultBackupStore:
      backupTarget: "s3://longhorn.mizuto.backup@eu-central-1/"
      backupTargetCredentialSecret: longhorn-wasabi-access
      pollInterval: 300
