apiVersion: v1
kind: Secret
metadata:
  name: longhorn-wasabi-access
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:X03rg4EFnCG448NgrWqPaV//3Vk=,iv:VJYcjfTeD7OwFmUmdNOMNrn75wWf6mjSRZK6/Z2kCxI=,tag:m2wbDD1z3sAK/y9FO7lliQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:4kyJGVHZ2zdjIW0pJPhaUITlJIRf0M/kaqinCtk6GPvBrDHoz157hw==,iv:4wINCF1PdOZH4Jv0qpaamEGerwFmUK2p7zUDHARwDKI=,tag:PTgYFE4eENKJYWRQVbYA6g==,type:str]
  AWS_ENDPOINTS: ENC[AES256_GCM,data:E62TD/pMzdeuDTiMe/swvNpV6/OeI8zKr6i3t1SshzwwRuO6eA==,iv:uFIA4Km2jvvNogs08NvIs2AlIpuP8Ndnv7GaQtUoSyo=,tag:MKKQLoXV/lxG5ArNpq9VSA==,type:str]
sops:
  age:
    - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZXkzb0k0SVByK3FFaWhG
        K0Q4bW1RbVV2djh1bHljMkQ1bGU1M0Q1SWxjCjRZQmd1R09VRUN4ZUdiZGg2bUE5
        M2pVQVZHR2srTnczMElwRkhMV3o1YTgKLS0tIG1GUXFSMDhrdkJxNWU1b1dDbGJq
        ck9xQ1JYYm9Hb1hUV0FRdmtiOE5JY0UKHDWueKEEmeu0I1IkiIHVsflAQag7iMtQ
        060KSRUloikkWhKebz9IsWcj3aMQ7N7UOYQM/IuVHXYjkPvBsHIjMw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-11T10:03:39Z"
  mac: ENC[AES256_GCM,data:xJ5TbR/1u1aJYG0A0t6REfzslmORyyBGNWs/UN4AJm5/6Qc3G8StE37kQLMlGvTt2Nd0mBoe7zAvOR2qqzr8D/eIr3fPZZO5OsxdVM1rJihfOKXGP2j7diDpW3iGUcbC/XJLLwG7E/nUsNS/fUdx92GGk8x1C21EFOsqVmwG3v8=,iv:sEX/dofEl/TM+UUGZ4ZO4Cb9pyjNDDC7zVtBaR+pVxw=,tag:NeqeZoiXA9687zlVFDzAmw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
