apiVersion: v1
kind: Secret
metadata:
  name: riva-secret
type: Opaque
stringData:
  mariadb-password: ENC[AES256_GCM,data:JZRbKbOEZyozFsfPDDFUgajNlJrOozVUHEeYy0oWaPuIezDo7TwkkZB1VMCNQnA2Tg3n1GAfxA3AjVNFHQXR9g==,iv:ltC1uWsL5S5MH0pbOJWn0MwJrs/O1FX7aIu9sdUUT1w=,tag:YIIPkVi6SpbubknzidR6Dg==,type:str]
  wordpress-password: ENC[AES256_GCM,data:ZZBtPwOCzjldZjSSrhBAgBRJn2tQujBK3olXIdd4JuIPgu5ZdETyig/8AGa8nxSzAZfQS+W67ehW2o7K/Fi0hA==,iv:OEuPhbTavZdgCd9WHuok9aP65c8XsCWtmMSj4ceFXH8=,tag:z4xpdCBicRj2Go9YCJH4eQ==,type:str]
sops:
  age:
    - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcGhEcmpTaDVtNXR0SmxT
        V1hwRzdCdWFkbW9TWTYzZ1Q0WnZrMVdXQW5BCndmVGVVUFMvNDdHYnJxTUI0UFBw
        S1NJd00raDVVdkZCMHNOemR3TTlsMlkKLS0tIDNtZk1yOFJaYjdtZlRuV29hWXZx
        TkZ1K0ZETjdwMUdXNkpzQ1BobkhKbFUKq1Jw5/pE7+iMMfd+0FGNQbJDACCs7qKi
        n58gryjXxc6DPdYqcGgQpFBwYCFQMR/nHrZAvdAcu2sX1RdjHY/Q7Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-23T21:50:07Z"
  mac: ENC[AES256_GCM,data:20GQ/76LguTWJHTZzIkcoIMuQclRuwixDaMg+uxbVOIqsOQFxwXLVw5nLljDQJZqd2I2i9iF0tYerQBjW2UNvQhW/sMFCqa8HlewArdccx1ULsDPYHniej0Y744oF0UZRcIBtO6VDd3jndDNviySMnZHe9yJMdw2JRUvHvZUwhw=,iv:EPJEoXwaq3I0jXlONexZrKeE8UKuSGhGSG1l4zkom8c=,tag:pwfu3Rv5WQSdzBeqANLp3w==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
