---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: slskd
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      slskd:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/slskd/slskd
              tag: 0.23.2@sha256:28df5325f301537ea8669b2ef90112a30cc9f2efd3eb714c9a778460b5dc6288
            env:
              DOTNET_BUNDLE_EXTRACT_BASE_DIR: /tmp/.net
              TZ: Europe/Amsterdam
              SLSKD_APP_DIR: /config
              SLSKD_HTTP_PORT: &port 80
              SLSKD_NO_AUTH: true
              SLSKD_NO_HTTPS: true
              SLSKD_SLSK_LISTEN_PORT: &soulseekPort 50300
            envFrom:
              - secretRef:
                  name: slskd-secret
                  #            probes:
                  #              liveness: &probes
                  #                enabled: true
                  #                custom: true
                  #                spec:
                  #                  httpGet:
                  #                    path: /health
                  #                    port: *port
                  #                  initialDelaySeconds: 1200
                  #                  periodSeconds: 30
                  #                  timeoutSeconds: 30
                  #                  failureThreshold: 10
                  #              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 1Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101000
        runAsGroup: 101000
        fsGroup: 101000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: {type: RuntimeDefault}
    service:
      app:
        forceRename: "{{ .Release.Name }}"
        primary: true
        ports:
          http:
            port: *port
      soulseek:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: "${CLUSTER_SOULSEEK_IP}"
        ports:
          soulseek:
            port: *soulseekPort
            protocol: TCP
    serviceMonitor:
      app:
        serviceName: slskd
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        storageClass: local-hostpath
        size: 5Gi
        globalMounts:
          - path: /config
      config-file:
        type: configMap
        name: slskd-configmap
        globalMounts:
          - path: /config/slskd.yml
            subPath: slskd.yml
            readOnly: true
      tmp:
        type: emptyDir
      media:
        type: nfs
        server: "${LAN_TRUENAS_IP}"
        path: /mnt/MAIN/media
        globalMounts:
          - path: /mnt/general
      music:
        type: nfs
        server: "${LAN_TRUENAS_IP}"
        path: /mnt/MAIN/miscellaneous/music
        globalMounts:
          - path: /mnt/general/music
