---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app home-assistant
  namespace: &namespace home
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/gatus/external
  dependsOn:
    - name: user-apps-mosquitto
      namespace: home
    - name: user-apps-zigbee2mqtt
      namespace: home
    - name: cluster-apps-longhorn
      namespace: storage
    - name: cluster-apps-cloudnative-pg-cluster
      namespace: database
  interval: 1h
  path: ./kubernetes/apps/home/home-assistant/app
  postBuild:
    substitute:
      APP: *app
      APP_NAME: "Home Assistant"
      GATUS_SUBDOMAIN: home
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - name: cluster-settings
        kind: ConfigMap
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
