---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-grafana
  namespace: &namespace observability
spec:
  path: ./kubernetes/apps/observability/grafana/app
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 10m
  targetNamespace: *namespace
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-grafana-instance
spec:
  dependsOn:
    - name: cluster-apps-grafana
  interval: 1h
  path: ./kubernetes/apps/observability/grafana/instance
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: observability
  wait: false
