---
apiVersion: v1
kind: ConfigMap
metadata:
  name: meilisearch-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: Meilisearch
        group: infrastructure
        url: http://meilisearch.utilities:7700/health
        interval: 1m
        ui:
          hide-url: true
          hide-hostname: true
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: discord
