---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: zone-configurator
  namespace: &namespace home
spec:
  path: ./kubernetes/apps/home/zone-configurator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: true
  interval: 15m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: cluster-apps-longhorn
      namespace: storage
