apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:X1GUZJwx+GbwqD5mrUFhknkz0P3dS1oMbfucp41bLC1Ur+vhYrpo1pOPpNYODiDV8+2Ctl/ALZKv18nmaiTLJBevM4EgIQ3BHjI=,iv:DptPW+jch7Auu1CfiW26MF4iNHxNCfOLlqIkQnXw9w4=,tag:iB9Bap9vkXj/nQkluSpisw==,type:str]
sops:
  age:
    - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTmZkUlcrWmtIS0s2bUhk
        NVJVT3I5aGVDQ3RJR2RKK1ZvK25WOURvYldNClhvd1ZkYWs4d2phdnBjN3UxYW8z
        MDBUSmdhRWlXSEU0WlJLQnFIa3E5dVUKLS0tIFRLSk03TVg3QmNaOVI3eVNtSDM1
        UmcxNUZJZUVqc3plYlpCY2JaVlFqTDAKHft9AAnBQnCeoeNFzST0ck0D3N+IdliS
        F+z9RIr6BSSU9dqMrv8QdQ9qJYsWRVl4B4sbB0wDgq8XbviNDuos8A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-28T16:18:34Z"
  mac: ENC[AES256_GCM,data:IFXtz8T/rA01GA4nVlIJzMK9OBTaaQw4iZbIicsjDj1kjCgPH8HV/OKJDb+4bmgS64KXkf4/NG7jQ4Q9LOfLzJ0ODPfDkIr5TWDdGH5ao8IP647kzGpNVpgarDLkCZYrxFeuxoWsGQV1CUFqmeqCO+zt0Q3fGAXDJXhD4VsE6c8=,iv:dREbB5nVhlgknCtf8yT9ZJ9VGYvl4mSphrQlGWxNJYQ=,tag:gXUbmHv/xTQ/CXGj8gXdvQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
